# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

# @deprecation - remove require after deprecating Rails 4
require_relative '../../lib/sub_test_task_patch'

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
